################################# Default configuration ###################
baseURL = "https://doococo.style/"
title = "DooCoco"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "plugins/ekko-lightbox/dist/ekko-lightbox.min.js"

############################# Navigation ##################################
# [[menu.main]]
# name = "about"
# pre = "#"
# url = "about"
# weight = 1
#
# [[menu.main]]
# name = "New"
# pre = "#"
# url = "season1"
# weight = 2
#
# [[menu.main]]
# name = "portfolio"
# pre = "#"
# url = "portfolio"
# weight = 3
#
# [[menu.main]]
# name = "team"
# pre = "#"
# url = "team"
# weight = 4
#
# # [[menu.main]]
# # name = "pricing"
# # pre = "#"
# # url = "pricing"
# # weight = 5
#
# [[menu.main]]
# name = "blog"
# pre = "#"
# url = "blog"
# weight = 6
#
# [[menu.main]]
# name = "contact"
# pre = "#"
# url = "contact"
# weight = 7
#
# [[menu.main]]
# name = "themefisher"
# pre = ""
# url = "https://themefisher.com/"
# weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# logo_width = "150px"
logo_width = "300px"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "G-LXEZTH79DX" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2020 DooCoco"
 # & Developed by [Gethugothemes](https://gethugothemes.com)"

[[Languages.en.menu.main]]
name = "new"
pre = "#"
url = "season1"
weight = 1

[[Languages.en.menu.main]]
name = "message"
pre = "#"
url = "testimonial"
weight = 2

[[Languages.en.menu.main]]
name = "about"
pre = "#"
url = "about"
weight = 3


[[Languages.en.menu.main]]
name = "portfolio"
pre = "#"
url = "portfolio"
weight = 4


# [[Languages.en.menu.main]]
# name = "pricing"
# pre = "#"
# url = "pricing"
# weight = 5

# [[Languages.en.menu.main]]
# name = "blog"
# pre = "#"
# url = "blog"
# weight = 6

[[Languages.en.menu.main]]
name = "contact"
pre = "#"
url = "contact"
weight = 7

################################ France Language ########################
[Languages.cn]
languageName = "中 文"
languageCode = "cn-cn"
contentDir = "content/chinese"
weight = 2
home = "Accueil"
# copyright = "Copyright &copy; 2020 DooCoco - ssssssDesigned by [Themefisher](https://themefisher.com)"
copyright = "Copyright &copy; 2020 DooCoco"

# & Developed by [Gethugothemes](https://gethugothemes.com)"

[[Languages.cn.menu.main]]
name = "新品"
pre = "cn/#"
url = "season1"
weight = 1

[[Languages.cn.menu.main]]
name = "寄语"
pre = "cn/#"
url = "testimonial"
weight = 2

[[Languages.cn.menu.main]]
name = "关于"
pre = "cn/#"
url = "about"
weight = 3

[[Languages.cn.menu.main]]
name = "产品"
pre = "cn/#"
url = "portfolio"
weight = 4

# [[Languages.cn.menu.main]]
# name = "价格"
# pre = "cn/#"
# url = "pricing"
# weight = 5

# [[Languages.cn.menu.main]]
# name = "日志"
# pre = "cn/#"
# url = "blog"
# weight = 6

[[Languages.cn.menu.main]]
name = "联络"
pre = "cn/#"
url = "contact"
weight = 7
